[Open Screen] Rolling 2 dependencies
Roll buildtools/ 8d2132841..204a35a2a (19 commits)

https://chromium.googlesource.com/chromium/src/buildtools/+log/8d2132841536..204a35a2a64f

$ git log 8d2132841..204a35a2a --date=short --no-merges --format='%ad %ae %s'
2020-04-23 thakis Reland "Roll libunwind 43bb9f8722..d999d54f4b"
2020-03-30 tvanderlippe Update clang-format version to eb85e90350e
2020-03-23 brettw Roll GN from 9499562d..5ed3c9cc
2020-03-12 agrieve Roll GN from fd3d768b..9499562d
2020-03-10 thakis roll gn 4166e9fbc1f..fd3d768bcfd4
2020-02-29 xiaohuic Clean up buildtools repo migration code
2020-02-24 thakis Revert "Roll libunwind 43bb9f8722..d999d54f4b"
2020-02-21 thakis Roll libunwind 43bb9f8722..d999d54f4b
2020-02-21 seblalancette Roll GN from 97cc440d..4166e9fb
2020-02-21 bpastene Reland: Pull libunwind, libcxx, libcxxabi from a different mirror.
2020-02-19 bpastene Revert "Pull libunwind, libcxx, libcxxabi from a different mirror."
2020-02-19 thakis Pull libunwind, libcxx, libcxxabi from a different mirror.
2020-01-28 thakis Roll GN 83dad00a:97cc440d
2020-01-28 thakis Reformat remaining gn files.
2020-01-21 sdefresne Roll GN 0c5557d173..83dad00afb
2020-01-16 thakis Reformat all gn files in /buildtools/third_party/libc++.
2020-01-16 felipesalazar Include cxa_thread_atexit on linux targets.
2020-01-13 thakis Roll GN a5bcbd726a..0c5557d17
2020-01-08 bpastene Update //buildtools/README.txt after it was merged into chromium.

Roll third_party/googletest/src/ 8697709e0..0eea2e9fc (141 commits)

https://chromium.googlesource.com/external/github.com/google/googletest.git/+log/8697709e0308..0eea2e9fc634

$ git log 8697709e0..0eea2e9fc --date=short --no-merges --format='%ad %ae %s'
2020-04-30 absl-team Googletest export
2020-04-28 absl-team Googletest export
2020-04-27 absl-team Googletest export
2020-04-24 absl-team Googletest export
2020-04-23 absl-team Googletest export
2020-04-20 absl-team Googletest export
2020-04-20 absl-team Googletest export
2020-04-17 absl-team Googletest export
2020-03-28 arthur.j.odwyer Add -Wdeprecated to the build configuration.
2020-04-16 arthur.j.odwyer Fix a -Wdeprecated warning.
2020-04-16 arthur.j.odwyer Fix a -Wdeprecated warning.
2020-04-16 arthur.j.odwyer Fix a -Wdeprecated warning.
2020-04-16 arthur.j.odwyer Remove all uses of GTEST_DISALLOW_{MOVE_,}ASSIGN_.
2020-04-19 igor.n.nazarenko Enable protobuf printing for open-source proto messages.
2020-04-16 arthur.j.odwyer VariadicMatcher needs a non-defaulted move constructor for compile-time performance.
2020-04-10 absl-team Googletest export
2020-04-12 jbohl fix signed/unsigned comparison issue (on OpenBSD)
2020-04-09 malcolm.parsons Remove redundant .c_str()
2020-04-06 mail gtest-unittest-api_test - fix warning in clang build
2020-04-01 absl-team Googletest export
2020-04-05 jijyunneng Remove duplicate codes existed in get-nprocessors.sh
2020-03-30 absl-team Googletest export
2020-03-28 arthur.j.odwyer Replace the last instance of `throw()` with `noexcept`. NFC.
2020-03-28 arthur.j.odwyer Fix a typo in .travis.yml
2020-03-23 absl-team Googletest export
2020-03-24 krystian.kuzniarek remove chapters on Autotools, Meson and plain Makefiles
2020-03-24 krystian.kuzniarek remove dead code in googletest-output-test
2020-03-24 pkryger Swap settimer and sigaction calls to avoid SIGPROF
2020-03-21 ngompa13 Ensure that gtest/gmock pkgconfig requirements specify version
2020-03-20 absl-team Googletest export
2019-07-11 adam.f.badura Add support for std::function in MockFunction (#2277)
2019-12-26 adam.f.badura Add tests for MockFunction deduction (#2277)
2020-03-17 absl-team Googletest export
2020-03-16 dmauro Googletest export
2020-03-13 absl-team Googletest export
2020-03-06 absl-team Googletest export
2020-03-03 absl-team Googletest export
2020-03-03 absl-team Googletest export
2020-03-11 romain.geissler Make sure IsATTY does not clobber errno.
2020-02-27 absl-team Googletest export
2020-02-25 absl-team Googletest export
2020-02-19 absl-team Googletest export
2020-02-21 johan.mabille Fixed warnings
2020-02-12 absl-team Googletest export
2020-02-11 absl-team Googletest export
2020-02-11 absl-team Googletest export
2020-02-10 absl-team Googletest export
2020-02-10 absl-team Googletest export
2020-02-07 absl-team Googletest export
2020-02-07 absl-team Googletest export
(...)
2019-12-17 kontakt Disable move constructor and assignment operator for test classes.
2019-12-16 krzysio Googletest export
2019-12-10 syoussefi Revert "Googletest export": disallow empty prefix
2019-12-10 syoussefi Revert "Googletest export": Remove test for empty prefix
2019-12-16 syoussefi Workaround VS bug w.r.t empty arguments to macros
2019-12-12 absl-team Googletest export
2019-12-11 absl-team Googletest export
2019-12-10 absl-team Googletest export
2019-12-06 misterg Googletest export
2019-12-13 kravlala.1 Activate GNU extensions in case of MSYS generator
2019-12-05 absl-team Googletest export
2019-12-05 absl-team Googletest export
2019-12-05 absl-team Googletest export
2019-12-02 absl-team Googletest export
2019-11-27 krystian.kuzniarek Revert "remove MSVC workaround: wmain link error in the static library"
2019-11-27 krystian.kuzniarek Revert "unify googletest and googlemock main functions"
2019-11-27 Oleksandr.Yefremov Rename test case to test suite
2019-11-26 absl-team Googletest export
2019-11-25 absl-team Googletest export
2019-11-25 mate.pek README.md: added Catch2 and Google Test Explorer
2019-11-25 maximilianschwab Fixed typo
2019-11-22 absl-team Googletest export
2019-11-20 absl-team Googletest export
2019-11-17 krystian.kuzniarek unify googletest and googlemock main functions
2019-11-17 krystian.kuzniarek remove MSVC workaround: wmain link error in the static library
2019-11-22 krystian.kuzniarek remove Nokia's Symbian compiler workaround: SafeMatcherCastImpl
2019-11-22 krystian.kuzniarek consistency fix for SafeMatcherCastImpl member functions
2019-11-17 krystian.kuzniarek remove MSVC workaround: cease const dropping
2019-11-17 krystian.kuzniarek remove MSVC workaround: warning 4355
2019-11-14 krystian.kuzniarek remove MSVC workaround: error C2665
2019-11-14 krystian.kuzniarek remove MSVC workaround: accessing namespace scope from within nested classes
2019-11-22 krystian.kuzniarek remove stale comments about older GCC versions
2019-11-22 krystian.kuzniarek remove g++ 2.95.0 workaround: no space after first comma in macros
2019-11-22 krystian.kuzniarek remove g++ 3.3 workaround: using on operator<<
2019-11-21 Christoph.Strehle Fix compile break for Microsoft Visual Studio 2017 v141
2019-11-19 absl-team Googletest export
2019-11-18 absl-team Googletest export
2019-11-16 xyb Fix internal memory leak in Windows _Crt report.
2019-11-15 b.gianfo Fix FlatTuple compilation on older msvc.
2019-11-11 krystian.kuzniarek add documentation for the premature-exit-file protocol
2019-11-08 absl-team Googletest export
2019-11-05 absl-team Googletest export
2019-10-19 martinerikwerner pkg-config: Remove pthread link flag from Cflags
2019-11-05 krystian.kuzniarek change incorrect comments
2019-11-05 krystian.kuzniarek update gen_gtest_pred_impl.py
2019-11-02 krystian.kuzniarek fix a typo
2019-11-02 krystian.kuzniarek pump.py: add support for Python 3
2019-11-02 krystian.kuzniarek update pump_manual.md
2019-08-06 ihor.youw Added special catch for std::exception in GTEST_TEST_NO_THROW_
2019-10-18 dieter.gnaier Fix Issue 2418

Created with:
  roll-dep buildtools third_party/chromium_quic/src third_party/googletest/src third_party/libfuzzer/src third_party/mDNSResponder/src
R=jopbha@chromium.org

Bug: b/155688981
Change-Id: I56cdbc88e0094a88676b4e993c237e95d592a2e2