Update patch set 7
Patch Set 7:

It looks like this broke upstream:

[17089/27472] CXX obj/chrome/browser/media/router/router/task_runner.o
FAILED: obj/chrome/browser/media/router/router/task_runner.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
In file included from ../../chrome/browser/media/router/providers/openscreen/platform/task_runner.cc:14:
../../chrome/browser/media/router/providers/openscreen/platform/task_runner.h:14:7: error: abstract class is marked 'final' [-Werror,-Wabstract-final-class]
class ChromeTaskRunner final : public TaskRunner {

Can this be reverted and relanded not to be pure virtual?  (Or use #ifdefs, but that seems like more work.)

Patch-set: 7
Reviewer: Gerrit User 1001982 <1001982@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>