Fix chromium compilation in linux-rel
Currently, linux-rel fails to build due to an unused return value
warning:

../../third_party/openscreen/src/platform/base/logging.cc:42:3: error: ignoring
return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
  write(g_log_fd, ss.str().c_str(), ss.str().size());

This patch fixes this issue by DCHECKing the return.