Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review+1
> 
> > Patch Set 1:
> > 
> > Seeing build issues from the fuzzing test additions on my macbook, does this look right?
> 
> Yes, that's a good catch.  What build command is actually failing though?  I thought |seed_corpus| wasn't actually being used except by ClusterFuzz?

Seed corpus, at least on my macbook, is picked up as part of the normal build. I don't think I'm doing anything fancy??

```
/usr/local/src/openscreen /usr/local/src ~/Dotfiles ~
ninja: Entering directory `out/Default'
[1/1] Regenerating ninja files
[1/8] ACTION //cast/common:message_framer_fuzzer_seed_corpus(//build/toolchain/mac:clang)
FAILED: message_framer_fuzzer_seed_corpus.zip 
python ../../testing/libfuzzer/archive_corpus.py --output message_framer_fuzzer_seed_corpus.zip ../../cast/common/message_framer_fuzzer_seeds
Traceback (most recent call last):
  File "../../testing/libfuzzer/archive_corpus.py", line 58, in <module>
    main()
  File "../../testing/libfuzzer/archive_corpus.py", line 36, in main
    directory)
Exception: The given seed_corpus directory (../../cast/common/message_framer_fuzzer_seeds) does not exist.
[5/8] CXX obj/cast/standalone_receiver/cast_receiver.main.o
ninja: build stopped: subcommand failed.
```

Patch-set: 1
Reviewer: Gerrit User 1323871 <1323871@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0