Create patch set 5
Change has been successfully rebased and submitted as 5d694418bc76f66463f06ce141c375062b0ba3b0

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: PRESUBMIT.py
Insertions: 72, Deletions: 65.

@@ -1,11 +1,18 @@
-# Copyright (c) 2018 The Chromium Authors. All rights reserved.
+# Copyright 2018 The Chromium Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
+# pragma pylint: disable=invalid-name, import-error
+"""
+This file acts as a git pre-submission checker, and uses the support tooling
+from depot_tools to check a variety of style and programming requirements.
+"""
 
+from collections import namedtuple
 import os
 import re
 import sys
 
+
 _REPO_PATH = os.path.dirname(os.path.realpath('__file__'))
 _IMPORT_SUBFOLDERS = ['tools', os.path.join('buildtools', 'checkdeps')]
 
@@ -13,37 +20,29 @@
 # we extend the system path instead.
 sys.path.extend(os.path.join(_REPO_PATH, p) for p in _IMPORT_SUBFOLDERS)
 
-import licenses
-from checkdeps import DepsChecker
+from checkdeps import DepsChecker  # pylint: disable=wrong-import-position
+import licenses  # pylint: disable=wrong-import-position
 
 # Opt-in to using Python3 instead of Python2, as part of the ongoing Python2
 # deprecation. For more information, see
 # https://issuetracker.google.com/173766869.
 USE_PYTHON3 = True
 
-# Rather than pass this to all of the checks, we override the global excluded
-# list with this one.
-_EXCLUDED_PATHS = (
-  # Exclude all of third_party/ except for BUILD.gns that we maintain.
-  r'third_party[\\\/].*(?<!BUILD.gn)$',
-
-  # Output directories (just in case)
-  r'.*\bDebug[\\\/].*',
-  r'.*\bRelease[\\\/].*',
-  r'.*\bxcodebuild[\\\/].*',
-  r'.*\bout[\\\/].*',
-
-  # There is no point in processing a patch file.
-  r'.+\.diff$',
-  r'.+\.patch$',
-)
-
 
 def _CheckLicenses(input_api, output_api):
     """Checks third party licenses and returns a list of violations."""
-    return [
-        output_api.PresubmitError(v) for v in licenses.ScanThirdPartyDirs()
-    ]
+    # NOTE: the licenses check is confused by the fact that we don't actually
+    # check ou the libraries in buildtools/third_party, so explicitly exclude
+    # that folder. See https://crbug.com/1215335 for more info.
+    licenses.PRUNE_PATHS.add(os.path.join('buildtools', 'third_party'))
+
+    if any(s.LocalPath().startswith('third_party')
+           for s in input_api.change.AffectedFiles()):
+        return [
+            output_api.PresubmitError(v)
+            for v in licenses.ScanThirdPartyDirs()
+        ]
+    return []
 
 
 def _CheckDeps(input_api, output_api):
@@ -54,43 +53,36 @@
     return [output_api.PresubmitError(v) for v in deps_results]
 
 
-# Matches OSP_CHECK(foo.is_value()) or OSP_DCHECK(foo.is_value())
-_RE_PATTERN_VALUE_CHECK = re.compile(
-    r'\s*OSP_D?CHECK\([^)]*\.is_value\(\)\);\s*')
+# Arguments passed to methods by cpplint.
+CpplintArgs = namedtuple("CpplintArgs", "filename clean_lines linenum error")
 
-# Matches Foo(Foo&&) when not followed by noexcept.
-_RE_PATTERN_MOVE_WITHOUT_NOEXCEPT = re.compile(
-    r'\s*(?P<classname>\w+)\((?P=classname)&&[^)]*\)\s*(?!noexcept)\s*[{;=]')
+# A defined error to return to cpplint.
+Error = namedtuple("Error", "type message")
 
 
-def _CheckNoRegexMatches(regex,
-                         filename,
-                         clean_lines,
-                         linenum,
-                         error,
-                         error_type,
-                         error_msg,
-                         include_cpp_files=True):
+def _CheckNoRegexMatches(regex, cpplint_args, error, include_cpp_files=True):
     """Checks that there are no matches for a specific regex.
 
   Args:
-    regex: regex to use for matching.
-    filename: The name of the current file.
-    clean_lines: A CleansedLines instance containing the file.
-    linenum: The number of the line to check.
-    error: The function to call with any errors found.
-    error_type: type of error, e.g. runtime/noexcept
-    error_msg: Specific message to prepend when regex match is found.
-  """
-    if not include_cpp_files and not filename.endswith('.h'):
+    regex: The regex to use for matching.
+    cpplint_args: The arguments passed to us by cpplint.
+    error: The error to return if we find an issue.
+    include_cpp_files: Whether C++ files should be checked.
+    """
+    if not include_cpp_files and not cpplint_args.filename.endswith('.h'):
         return
 
-    line = clean_lines.elided[linenum]
+    line = cpplint_args.clean_lines.elided[cpplint_args.linenum]
     matched = regex.match(line)
     if matched:
-        error(filename, linenum, error_type, 4,
-              'Error: {} at {}'.format(error_msg,
-                                       matched.group(0).strip()))
+        cpplint_args.error(
+            cpplint_args.filename, cpplint_args.linenum, error.type, 4,
+            f'Error: {error.message} at {matched.group(0).strip()}')
+
+
+# Matches OSP_CHECK(foo.is_value()) or OSP_DCHECK(foo.is_value())
+_RE_PATTERN_VALUE_CHECK = re.compile(
+    r'\s*OSP_D?CHECK\([^)]*\.is_value\(\)\);\s*')
 
 
 def _CheckNoValueDchecks(filename, clean_lines, linenum, error):
@@ -101,9 +93,17 @@
     linenum: The number of the line to check.
     error: The function to call with any errors found.
     """
-    _CheckNoRegexMatches(_RE_PATTERN_VALUE_CHECK, filename, clean_lines,
-                         linenum, error, 'runtime/is_value_dchecks',
-                         'Unnecessary CHECK for ErrorOr::is_value()')
+    cpplint_args = CpplintArgs(filename, clean_lines, linenum, error)
+    error_to_return = Error('runtime/is_value_dchecks',
+                            'Unnecessary CHECK for ErrorOr::is_value()')
+
+    _CheckNoRegexMatches(_RE_PATTERN_VALUE_CHECK, cpplint_args,
+                         error_to_return)
+
+
+# Matches Foo(Foo&&) when not followed by noexcept.
+_RE_PATTERN_MOVE_WITHOUT_NOEXCEPT = re.compile(
+    r'\s*(?P<classname>\w+)\((?P=classname)&&[^)]*\)\s*(?!noexcept)\s*[{;=]')
 
 
 def _CheckNoexceptOnMove(filename, clean_lines, linenum, error):
@@ -113,12 +113,19 @@
     clean_lines: A CleansedLines instance containing the file.
     linenum: The number of the line to check.
     error: The function to call with any errors found.
-  """
+    """
+    cpplint_args = CpplintArgs(filename, clean_lines, linenum, error)
+    error_to_return = Error('runtime/noexcept',
+                            'Move constructor not declared \'noexcept\'')
+
     # We only check headers as noexcept is meaningful on declarations, not
     # definitions.  This may skip some definitions in .cc files though.
-    _CheckNoRegexMatches(_RE_PATTERN_MOVE_WITHOUT_NOEXCEPT, filename,
-                         clean_lines, linenum, error, 'runtime/noexcept',
-                         'Move constructor not declared \'noexcept\'', False)
+    _CheckNoRegexMatches(_RE_PATTERN_MOVE_WITHOUT_NOEXCEPT, cpplint_args,
+                         error_to_return, False)
+
+
+# Gives additional debug information whenever a linting error occurs.
+_CPPLINT_VERBOSE_LEVEL = 4
 
 # - We disable c++11 header checks since Open Screen allows them.
 # - We disable whitespace/braces because of various false positives.
@@ -136,9 +143,9 @@
     files = [
         f.AbsoluteLocalPath() for f in input_api.AffectedSourceFiles(None)
     ]
-    CPPLINT_VERBOSE_LEVEL = 4
+
     for file_name in files:
-        cpplint.ProcessFile(file_name, CPPLINT_VERBOSE_LEVEL,
+        cpplint.ProcessFile(file_name, _CPPLINT_VERBOSE_LEVEL,
                             [_CheckNoexceptOnMove, _CheckNoValueDchecks])
 
     if cpplint._cpplint_state.error_count:
@@ -160,15 +167,18 @@
 
 
 def _CommonChecks(input_api, output_api):
+    """Performs a list of checks that should be used for both presubmission and
+       upload validation.
+    """
     # PanProjectChecks include:
     #   CheckLongLines (@ 80 cols)
     #   CheckChangeHasNoTabs
     #   CheckChangeHasNoStrayWhitespace
-    #   CheckLicense
     #   CheckChangeWasUploaded (if committing)
     #   CheckChangeHasDescription
     #   CheckDoNotSubmitInDescription
     #   CheckDoNotSubmitInFiles
+    #   CheckLicenses
     results = input_api.canned_checks.PanProjectChecks(input_api,
                                                        output_api,
                                                        owners_check=False)
@@ -204,16 +214,13 @@
     results.extend(_CheckDeps(input_api, output_api))
 
     # Run tools/licenses on code change.
-    # TODO(https://crbug.com/1215335): licenses check is confused by our
-    # buildtools checkout that doesn't actually check out the libraries.
-    licenses.PRUNE_PATHS.add(os.path.join('buildtools', 'third_party'))
     results.extend(_CheckLicenses(input_api, output_api))
 
     return results
 
 
 def CheckChangeOnUpload(input_api, output_api):
-    input_api.DEFAULT_FILES_TO_SKIP = _EXCLUDED_PATHS
+    """Checks the changelist whenever there is an upload (`git cl upload`)"""
     # We always run the OnCommit checks, as well as some additional checks.
     results = CheckChangeOnCommit(input_api, output_api)
     results.extend(
@@ -222,5 +229,5 @@
 
 
 def CheckChangeOnCommit(input_api, output_api):
-    input_api.DEFAULT_FILES_TO_SKIP = _EXCLUDED_PATHS
+    """Checks the changelist whenever there is commit (`git cl commit`)"""
     return _CommonChecks(input_api, output_api)
```


Patch-set: 5
Patch-set-description: Rebase
Subject: [Infra] Re-enable licenses check
Status: merged
Commit: 5d694418bc76f66463f06ce141c375062b0ba3b0
Tag: autogenerated:gerrit:merged
Groups: 3205619e60d925a57fed5473e1ef06390daae8fb
Label: Code-Review=+1, 569f65c1b155d3816c08e6e4f3e12931b4209cfc Gerrit User 1001982 <1001982@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, b0fa4888c5e9607648707abb4ab731392d6dd7c7 Gerrit User 1323871 <1323871@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, dd9073919f8ee1863b1b645cf530211172d305b3
Submission-id: 4263102
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Code-Coverage
Submitted-with: MAY: Code-Review: Gerrit User 1001982 <1001982@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1323871 <1323871@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Feels
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners